import localFont from 'next/font/local'
import './globals.css'

const satoshiVariable = localFont({
  src: [
    {
      path: '../public/fonts/satoshi-variable/Satoshi-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-satoshiVariable',
})

const minecraft = localFont({
  src: [
    {
      path: '../public/fonts/minecraft-font/MinecraftRegular-Bmg3.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-minecraft',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satoshiVariable.variable} ${minecraft.variable}`}>{children}</body>
    </html>
  )
}
