import localFont from 'next/font/local'
import './globals.css'

const satoshiVariable = localFont({
  src: [
    {
      path: './assets/fonts/satoshi-variable/Satoshi-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={satoshiVariable.className}>{children}</body>
    </html>
  )
}
